# Generated by Django 4.2.8 on 2024-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='price',
        ),
        migrations.AddField(
            model_name='battery',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='batterycategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='batterycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
