# Generated by Django 4.2.8 on 2024-01-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_remove_battery_description_remove_battery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='batteryBrand',
            new_name='brand',
        ),
    ]
