# Generated by Django 4.2.8 on 2024-02-08 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'enginebrandes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineOilCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('decription', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineoil.engineoilcategory')),
            ],
            options={
                'verbose_name_plural': 'enginecategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil_type', models.CharField(max_length=100)),
                ('engine_size', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_address', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arrivaltime', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandes', to='engineoil.enginebrand')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicleinformation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilengine', to='engineoil.engineoilcategory')),
            ],
        ),
    ]
