# Generated by Django 4.2.8 on 2024-01-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineoil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineoil',
            old_name='enginebrand',
            new_name='brand',
        ),
    ]
