# Generated by Django 4.2.8 on 2024-01-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineoil', '0002_rename_enginebrand_engineoil_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineoil',
            name='price',
        ),
        migrations.AddField(
            model_name='engineoil',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='engineoil',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandes', to='engineoil.enginebrand'),
        ),
    ]
