# Generated by Django 4.2.8 on 2024-01-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineoil', '0003_remove_engineoil_price_engineoil_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineoil',
            name='description',
        ),
    ]
