# Generated by Django 4.2.8 on 2024-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineoil', '0004_remove_engineoil_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineoilcategory',
            name='decription',
            field=models.TextField(default=''),
        ),
    ]
