# Generated by Django 4.2.8 on 2024-01-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='price',
        ),
    ]
