# Generated by Django 4.2.8 on 2024-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyre', '0002_remove_tyre_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
