# Generated by Django 4.2.8 on 2024-02-08 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'brandes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.fuelcategory')),
            ],
            options={
                'verbose_name_plural': 'fuelcategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GasLineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_address', models.CharField(max_length=255)),
                ('arrivaltime', models.DateTimeField(default=django.utils.timezone.now)),
                ('fuel_type', models.CharField(default=True, max_length=200)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandes', to='fuel.fuelbrand')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='base.vehicleinformation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaslines', to='fuel.fuelcategory')),
            ],
        ),
    ]
