# Generated by Django 4.2.8 on 2024-01-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaslinedetails',
            name='price',
        ),
        migrations.AddField(
            model_name='gaslinedetails',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
