# Generated by Django 4.2.8 on 2024-01-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('fuel', '0002_remove_gaslinedetails_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaslinedetails',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='base.vehicleinformation'),
        ),
    ]
