# Generated by Django 4.2.8 on 2023-12-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='adminuser',
        ),
    ]
