# Generated by Django 4.2.8 on 2024-02-09 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_newuser_driver_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('country_of_registration', models.CharField(blank=True, help_text='Country of registration', max_length=50, null=True)),
                ('international_insurance_provider', models.CharField(blank=True, help_text='International insurance provider', max_length=50, null=True)),
                ('registration_expiration_date', models.DateField(blank=True, help_text='Date of registration expiration', null=True)),
                ('international_service_requirements', models.TextField(blank=True, help_text='International service requirements', null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
