# Generated by Django 4.2.8 on 2023-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_adminuser_password_remove_newuser_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
