# Generated by Django 4.2.8 on 2024-01-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.productinventory'),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='productinventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productattributevaluess', to='inventory.productinventory'),
        ),
    ]
