# Generated by Django 4.2.8 on 2023-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinformation',
            name='booking',
        ),
    ]
