# Generated by Django 4.2.8 on 2023-12-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='regular_price',
        ),
    ]
