# Generated by Django 4.2.8 on 2024-01-12 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.carwashcategory')),
            ],
            options={
                'verbose_name_plural': 'carwashcategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarWashOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('typeofcarwash', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('description', models.TextField()),
                ('arrivaltime', models.DateTimeField(default=django.utils.timezone.now)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_types', to='base.vehicleinformation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwash', to='carwash.carwashcategory')),
            ],
        ),
    ]
