# Generated by Django 4.2.8 on 2024-01-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwashorder',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='carwashorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carwashorder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carwashorder',
            name='price',
        ),
        migrations.AddField(
            model_name='carwashcategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carwashorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
