name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
        with:
          FTP-SERVER: ftp.gooderash.com
          FTP-USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP-PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install lftp
        run: |
          sudo apt-get install -y lftp
      - name: Deploy to cPanel
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
